INSERT INTO siandalan_service_db.staff_role (nama,akses,wilayah,created_at,updated_at,deleted_at,default_status,watch_status) VALUES
	 ('ADMINISTRATOR','{"holiday":{"code":"holiday","name":"Hari libur","category":"master"},"category":{"code":"category","name":"Kategori","category":"master"},"bangkitan":{"code":"bangkitan","name":"Bangkitan","category":"master"},"document":{"code":"document","name":"Dokumen","category":"master"},"team":{"code":"team","name":"Tim Penilai","category":"master"},"applicant":{"code":"applicant","name":"Pemohon","category":"master"},"user":{"code":"user","name":"User","category":"master"},"berkas":{"code":"berkas","name":"Berkas","category":"master"},"faq":{"code":"faq","name":"F A Q","category":"master"},"initial_verification":{"code":"initial_verification","name":"Verifikasi Awal","category":"andalalin"},"manage_invitation":{"code":"manage_invitation","name":"Kelola Undangan","category":"andalalin"},"minutes_of_meeting":{"code":"minutes_of_meeting","name":"Berita Acara Rapat","category":"andalalin"},"final_verification":{"code":"final_verification","name":"Verifikasi Final","category":"andalalin"},"meeting_approval":{"code":"meeting_approval","name":"Persetujuan Rapat","category":"andalalin"},"sk_signature":{"code":"sk_signature","name":"Tangan SK","category":"andalalin"},"change_schedule":{"code":"change_schedule","name":"Ubah Jadwal","category":"andalalin"},"edit":{"code":"edit","name":"Edit","category":"andalalin"},"upload_docs":{"code":"upload_docs","name":"Upload Dokumen","category":"andalalin"},"generate_billing":{"code":"generate_billing","name":"Generate Billing","category":"andalalin"},"set_schedule":{"code":"set_schedule","name":"Tambah Jadwal","category":"andalalin"},"sip_verifikasi":{"code":"sip_verifikasi","name":"Verifikator","category":"penyusun"},"sip_jadwal":{"code":"sip_jadwal","name":"Penyusun Jadwal","category":"penyusun"}}','Pusat','2020-12-24 13:40:26','2023-03-06 08:39:09',NULL,'in_assistance',NULL),
	 ('VERIFIKATOR AWAL','{"initial_verification":{"code":"initial_verification","name":"Verifikasi Awal","category":"andalalin"},"holiday":{"code":"holiday","name":"Hari libur","category":"master"},"applicant":{"code":"applicant","name":"Pemohon","category":"master"},"sip_verifikasi":{"code":"sip_verifikasi","name":"Verifikasi","category":"penyusun"}}','Pusat','2020-12-24 13:40:26','2021-09-16 00:42:45',NULL,'',NULL),
	 ('VERIFIKATOR AKHIR','{"final_verification":{"code":"final_verification","name":"Verifikasi Final","category":"andalalin"}}','Pusat','2020-12-24 13:40:26','2021-01-11 07:08:27',NULL,NULL,NULL),
	 ('KASUBDIT','{"meeting_approval":{"code":"meeting_approval","name":"Persetujuan Rapat","category":"andalalin"},"sip_kasubdit":{"code":"sip_kasubdit","name":"Kasubdit","category":"penyusun"}}','Pusat','2020-12-24 13:40:26','2022-07-26 06:26:42',NULL,'',NULL),
	 ('DIREKTUR','{"sk_signature":{"code":"sk_signature","name":"Tanda Tangan SK","category":"andalalin"},"sip_direktur":{"code":"sip_direktur","name":"Direktur","category":"penyusun"}}','Pusat','2020-12-24 13:40:26','2021-11-24 00:44:21',NULL,'',NULL),
	 ('NOTULEN','{"manage_invitation":{"code":"manage_invitation","name":"Kelola Undangan","category":"andalalin"},"minutes_of_meeting":{"code":"minutes_of_meeting","name":"Berita Acara Rapat","category":"andalalin"},"holiday":{"code":"holiday","name":"Hari libur","category":"master"},"applicant":{"code":"applicant","name":"Pemohon","category":"master"}}','Pusat','2020-12-24 13:40:26','2021-01-11 07:09:41',NULL,'',NULL),
	 ('System Administrator','{"holiday":{"code":"holiday","name":"Hari libur","category":"master"},"category":{"code":"category","name":"Kategori","category":"master"},"bangkitan":{"code":"bangkitan","name":"Bangkitan","category":"master"},"applicant":{"code":"applicant","name":"Pemohon","category":"master"},"user":{"code":"user","name":"User","category":"master"},"berkas":{"code":"berkas","name":"Berkas","category":"master"},"setting":{"code":"setting","name":"Setting","category":"master"},"faq":{"code":"faq","name":"F A Q","category":"master"}}','pusat','2021-01-11 07:04:08','2022-02-20 06:17:19',NULL,'',NULL),
	 ('VERIFIKATOR TENAGA AHLI','{"sip_tim_penilai":{"code":"sip_tim_penilai","name":"Tim Penilai","category":"penyusun"},"sip_jadwal":{"code":"sip_jadwal","name":"Penyusun Jadwal","category":"penyusun"}}','pusat','2021-09-08 22:55:34','2021-09-22 20:35:19',NULL,'',NULL),
	 ('BENDAHARA','{"sip_bendahara":{"code":"sip_bendahara","name":"Bendahara","category":"penyusun"}}','pusat','2021-09-08 22:56:58','2021-09-08 23:05:16',NULL,'',NULL),
	 ('KEPOLISIAN','{"guest":{"code":"guest","name":"guest","category":"andalalin"}}','pusat','2023-06-20 04:24:18','2023-08-08 07:49:15',NULL,'signed',NULL)
	 ('PUPR','{"guest":{"code":"guest","name":"guest","category":"andalalin"}}','Pusat','2023-06-22 02:53:26','2023-08-08 07:49:02',NULL,'signed',NULL),
	 ('tess','{"holiday":{"code":"holiday","name":"Hari libur","category":"master"},"category":{"code":"category","name":"Kategori","category":"master"},"team":{"code":"team","name":"Tim Penilai","category":"master"},"user":{"code":"user","name":"User","category":"master"},"manage_invitation":{"code":"manage_invitation","name":"Kelola Undangan","category":"andalalin"},"minutes_of_meeting":{"code":"minutes_of_meeting","name":"Berita Acara Rapat","category":"andalalin"},"final_verification":{"code":"final_verification","name":"Verifikasi Final","category":"andalalin"},"sk_signature":{"code":"sk_signature","name":"Tangan SK","category":"andalalin"},"change_schedule":{"code":"change_schedule","name":"Ubah Jadwal","category":"andalalin"}}','pusat','2023-07-10 07:05:41','2023-07-10 07:05:41',NULL,'',NULL),
	 ('BPTD','{"guest":{"code":"guest","name":"guest","category":"andalalin"}}','Pusat','2023-08-08 07:49:33','2023-08-08 07:49:33',NULL,'signed',NULL);
